version: "3.9"

services:

  bot:
    container_name: telegram-app
    build: .
    image: shipaaa/telegram-sport-bot:latest
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"


  postgres-db:
    container_name: database-postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=postgres-db
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./pkg/models/tablesCreation.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./pkg/models/tablesFilling.sql:/docker-entrypoint-initdb.d/fill_tables.sql

volumes:
  database_postgres: