version: "3.9"

services:

  bot:
    container_name: telegram-app
    build: .
    command: ./bot
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"

  postgres-db:
    container_name: database-postgres
    restart: always
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./pkg/models/tablesCreation.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./pkg/models/tablesFilling.sql:/docker-entrypoint-initdb.d/fill_tables.sql

volumes:
  database_postgres: